# Generated by Django 3.2.4 on 2022-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=100)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('doj', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('aadharno', models.CharField(max_length=15)),
                ('panno', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
